// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Character struct {
	ID        int64
	Name      string
	LastCheck time.Time
	CreatedAt time.Time
}

type XpRecord struct {
	ID           int64
	Skill        string
	CharacterID  int64
	LastXpCount  int64
	LastLevel    int32
	LastPosition int64
	UpdatedAt    time.Time
	CreatedAt    time.Time
}
